<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240505165654 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Создание базовых таблиц: users, groups, skills';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(150) NOT NULL, name VARCHAR(120) NOT NULL, surname VARCHAR(120) NOT NULL, status SMALLINT DEFAULT 1 NOT NULL, roles JSON NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX users__email__uq ON users (email)');

        $this->addSql('CREATE TABLE groups (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, limit_teachers INT NOT NULL, limit_students INT NOT NULL, level SMALLINT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, skill_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX groups__name__idx ON groups (name)');
        $this->addSql('CREATE INDEX groups__skill__idx ON groups (skill_id)');

        $this->addSql('CREATE TABLE skills (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, level SMALLINT DEFAULT 1 NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX skills__name_level__uq ON skills (name, level)');
        $this->addSql('COMMENT ON TABLE skills IS \'Навык и уровень владения\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE skills');
        $this->addSql('DROP TABLE groups');
        $this->addSql('DROP TABLE users');
    }
}
