<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240511115736 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Создание промежуточных таблиц: group_user, user_skill';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE group_user (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, group_id BIGINT DEFAULT NULL, user_id BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX group_user__group_id__idx ON group_user (group_id)');
        $this->addSql('CREATE INDEX group_user__user_id__idx ON group_user (user_id)');
        $this->addSql('CREATE UNIQUE INDEX group_user__group_id_user_id__uq ON group_user (group_id, user_id)');

        $this->addSql('CREATE TABLE user_skill (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id BIGINT DEFAULT NULL, skill_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX user_skill__user_id__idx ON user_skill (user_id)');
        $this->addSql('CREATE INDEX user_skill__skill_id__idx ON user_skill (skill_id)');
        $this->addSql('CREATE UNIQUE INDEX user_skill__skill_id_user_id__uq ON user_skill (user_id, skill_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE group_user');
        $this->addSql('DROP TABLE user_skill');
    }
}
