<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240501201515 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Роль';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "roles" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX roles__name ON "roles" (name)');
        $this->addSql('CREATE TABLE "user_role" (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id BIGINT DEFAULT NULL, role_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX user_role__user_id ON "user_role" (user_id)');
        $this->addSql('CREATE INDEX user_role__role_id ON "user_role" (role_id)');
        $this->addSql('CREATE UNIQUE INDEX user_role__user_id_role_id ON "user_role" (user_id, role_id)');
        $this->addSql('ALTER TABLE "user_role" ADD CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user_role" ADD CONSTRAINT role_id FOREIGN KEY (role_id) REFERENCES "roles" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "user_role" DROP CONSTRAINT user_id');
        $this->addSql('ALTER TABLE "user_role" DROP CONSTRAINT role_id');
        $this->addSql('DROP TABLE "roles"');
        $this->addSql('DROP TABLE "user_role"');
    }
}
