<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241126144132 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Пересборка проекта, ииграции сброшены';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE groups (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, min_students INT NOT NULL, max_students INT NOT NULL, teacher_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX groups__name__idx ON groups (name)');
        $this->addSql('CREATE INDEX groups__teacher_id__idx ON groups (teacher_id)');
        $this->addSql('CREATE TABLE skill_proficiencies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, level INT NOT NULL, skill_id BIGINT NOT NULL, teacher_id INT DEFAULT NULL, student_id INT DEFAULT NULL, group_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FD1AE76A5585C142 ON skill_proficiencies (skill_id)');
        $this->addSql('CREATE INDEX IDX_FD1AE76A41807E1D ON skill_proficiencies (teacher_id)');
        $this->addSql('CREATE INDEX IDX_FD1AE76ACB944F1A ON skill_proficiencies (student_id)');
        $this->addSql('CREATE INDEX IDX_FD1AE76AFE54D947 ON skill_proficiencies (group_id)');
        $this->addSql('CREATE INDEX skill_proficiencies__level__idx ON skill_proficiencies (level)');
        $this->addSql('CREATE UNIQUE INDEX skill_proficiencies__unique_assignment ON skill_proficiencies (skill_id, teacher_id, student_id, group_id)');
        $this->addSql('CREATE TABLE skills (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(1000) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX skills__name__uq ON skills (name)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, max_groups INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE INDEX users__name__idx ON users (first_name, last_name)');
        $this->addSql('CREATE INDEX users__type__idx ON users (type)');
        $this->addSql('CREATE TABLE student_groups (student_id INT NOT NULL, group_id INT NOT NULL, PRIMARY KEY(student_id, group_id))');
        $this->addSql('CREATE INDEX IDX_7E5BE1F0CB944F1A ON student_groups (student_id)');
        $this->addSql('CREATE INDEX IDX_7E5BE1F0FE54D947 ON student_groups (group_id)');
        $this->addSql('ALTER TABLE groups ADD CONSTRAINT FK_F06D397041807E1D FOREIGN KEY (teacher_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE skill_proficiencies ADD CONSTRAINT FK_FD1AE76A5585C142 FOREIGN KEY (skill_id) REFERENCES skills (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE skill_proficiencies ADD CONSTRAINT FK_FD1AE76A41807E1D FOREIGN KEY (teacher_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE skill_proficiencies ADD CONSTRAINT FK_FD1AE76ACB944F1A FOREIGN KEY (student_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE skill_proficiencies ADD CONSTRAINT FK_FD1AE76AFE54D947 FOREIGN KEY (group_id) REFERENCES groups (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_groups ADD CONSTRAINT FK_7E5BE1F0CB944F1A FOREIGN KEY (student_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_groups ADD CONSTRAINT FK_7E5BE1F0FE54D947 FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE groups DROP CONSTRAINT FK_F06D397041807E1D');
        $this->addSql('ALTER TABLE skill_proficiencies DROP CONSTRAINT FK_FD1AE76A5585C142');
        $this->addSql('ALTER TABLE skill_proficiencies DROP CONSTRAINT FK_FD1AE76A41807E1D');
        $this->addSql('ALTER TABLE skill_proficiencies DROP CONSTRAINT FK_FD1AE76ACB944F1A');
        $this->addSql('ALTER TABLE skill_proficiencies DROP CONSTRAINT FK_FD1AE76AFE54D947');
        $this->addSql('ALTER TABLE student_groups DROP CONSTRAINT FK_7E5BE1F0CB944F1A');
        $this->addSql('ALTER TABLE student_groups DROP CONSTRAINT FK_7E5BE1F0FE54D947');
        $this->addSql('DROP TABLE groups');
        $this->addSql('DROP TABLE skill_proficiencies');
        $this->addSql('DROP TABLE skills');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE student_groups');
    }
}
