<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240515142505 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'hw4 Поменял связь между пользователями и ролями';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE user_role DROP CONSTRAINT user_role__user_id_fk');
        $this->addSql('ALTER TABLE user_role DROP CONSTRAINT user_role__role_id_fk');
        $this->addSql('DROP TABLE user_role');
        $this->addSql('DROP TABLE role');
        $this->addSql('ALTER TABLE users ADD roles JSON NOT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE user_role (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id BIGINT DEFAULT NULL, role_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX user_role__user_id_role_id__uq ON user_role (user_id, role_id)');
        $this->addSql('CREATE INDEX user_role__role_id__idx ON user_role (role_id)');
        $this->addSql('CREATE INDEX user_role__user_id__idx ON user_role (user_id)');
        $this->addSql('CREATE TABLE role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX roles__name__uq ON role (name)');
        $this->addSql('CREATE INDEX roles__name__idx ON role (name)');
        $this->addSql('ALTER TABLE user_role ADD CONSTRAINT user_role__user_id_fk FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_role ADD CONSTRAINT user_role__role_id_fk FOREIGN KEY (role_id) REFERENCES role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "users" DROP roles');
    }
}
