<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240501201522 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Группа';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "group_user" (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id BIGINT DEFAULT NULL, group_id BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX group_user__group_id ON "group_user" (group_id)');
        $this->addSql('CREATE INDEX group_user__user_id ON "group_user" (user_id)');
        $this->addSql('CREATE UNIQUE INDEX group_user__group_id_user_id ON "group_user" (group_id, user_id)');
        $this->addSql('CREATE TABLE "groups" (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, limit_teachers INT NOT NULL, limit_students INT NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, skill_id INT DEFAULT NULL, grade_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX group__name ON "groups" (name)');
        $this->addSql('CREATE UNIQUE INDEX group__skill_id ON "groups" (skill_id)');
        $this->addSql('CREATE UNIQUE INDEX group__grade_id ON "groups" (grade_id)');
        $this->addSql('ALTER TABLE "group_user" ADD CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "group_user" ADD CONSTRAINT group_id FOREIGN KEY (group_id) REFERENCES "groups" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "groups" ADD CONSTRAINT skill_id FOREIGN KEY (skill_id) REFERENCES "skill" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "groups" ADD CONSTRAINT grade_id FOREIGN KEY (grade_id) REFERENCES "grades" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "group_user" DROP CONSTRAINT user_id');
        $this->addSql('ALTER TABLE "group_user" DROP CONSTRAINT group_id');
        $this->addSql('ALTER TABLE "groups" DROP CONSTRAINT skill_id');
        $this->addSql('ALTER TABLE "groups" DROP CONSTRAINT grade_id');
        $this->addSql('DROP TABLE "group_user"');
        $this->addSql('DROP TABLE "groups"');
    }
}
